import openpyxl
import os

def main():
    excel_path = r"c:\Users\kajik\OneDrive\Desktop\BAL_STUDIO_SEARCH\data\config\NEXT_all_tags_classified.xlsx"
    ts_path = r"c:\Users\kajik\OneDrive\Desktop\BAL_STUDIO_SEARCH\src\data\tagCategories.ts"

    wb = openpyxl.load_workbook(excel_path, data_only=True)
    
    # Try to find sheet containing "全タグ" or "分類"
    sheet = None
    for name in wb.sheetnames:
        if "全タグ" in name or "分類" in name:
            sheet = wb[name]
            break
    if sheet is None:
        sheet = wb.worksheets[0]

    rows = list(sheet.iter_rows(values_only=True))

    tag_categories = []
    # Identify headers and find indices
    headers = [str(cell).strip() if cell is not None else "" for cell in rows[0]]
    
    # Defaults in case headers aren't exact
    cat_idx = 0
    order_idx = 1
    tag_idx = 2
    
    for i, h in enumerate(headers):
        if "カテゴリ" in h:
            cat_idx = i
        elif "表示順" in h:
            order_idx = i
        elif "タグ" in h:
            tag_idx = i

    for r in rows[1:]:
        if not r or len(r) <= max(cat_idx, order_idx, tag_idx):
            continue
        
        raw_cat = r[cat_idx]
        raw_order = r[order_idx]
        raw_tag = r[tag_idx]
        
        if raw_cat is None or raw_tag is None:
            continue
            
        category = str(raw_cat).strip()
        tag = str(raw_tag).strip()
        
        try:
            display_order = int(raw_order) if raw_order is not None else 999999
        except ValueError:
            display_order = 999999
            
        if tag:
            tag_categories.append({
                "tag": tag,
                "category": category,
                "displayOrder": display_order
            })

    # Format the TS content
    ts_content = "/* This file is auto-generated by scripts/generate-tag-categories.py */\n\n"
    ts_content += "export interface TagCategoryMap {\n"
    ts_content += "  tag: string;\n"
    ts_content += "  category: string;\n"
    ts_content += "  displayOrder: number;\n"
    ts_content += "}\n\n"
    ts_content += "export const tagCategories: TagCategoryMap[] = [\n"
    for item in tag_categories:
        escaped_tag = item["tag"].replace('"', '\\"')
        escaped_cat = item["category"].replace('"', '\\"')
        ts_content += f'  {{ tag: "{escaped_tag}", category: "{escaped_cat}", displayOrder: {item["displayOrder"]} }},\n'
    ts_content += "];\n"

    os.makedirs(os.path.dirname(ts_path), exist_ok=True)
    with open(ts_path, "w", encoding="utf-8") as f:
        f.write(ts_content)

    print(f"Generated {len(tag_categories)} tag categories at {ts_path}")

if __name__ == "__main__":
    main()
